# Generated by Django 3.0.7 on 2020-11-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201103_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img_profile',
            field=models.ImageField(default='default-plofile.png', upload_to='static\\img\\img_user', verbose_name='Фото пользователя'),
        ),
    ]
