# Generated by Django 3.0.7 on 2020-11-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_news_shop_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img_article',
            field=models.ImageField(default='default-article.jpg', upload_to='', verbose_name='Фото статьи'),
        ),
    ]
