# Generated by Django 3.0.7 on 2020-11-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201103_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img_article',
            field=models.ImageField(default='default-article.jpg', upload_to='static\\img\\img_article', verbose_name='Фото статьи'),
        ),
    ]
